# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^tests/.*data/.*$
      - id: check-json
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args:
          - "--profile=black"
          - "--line-length=100"
  - repo: https://github.com/psf/black
    # https://github.com/psf/black/blob/main/docs/integrations/source_version_control.md
    rev: 22.12.0
    hooks:
      - id: black
        name: black
        language_version: python3.9
        args: # arguments to configure black
          - "--line-length=100"
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=100"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.0"
    hooks:
      - id: poetry-check
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
            "--without-hashes",
          ]
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements-dev.txt",
            "--without-hashes",
            "--with",
            "dev",
          ]
