# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^tests/.*data/.*$
      - id: check-json
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args:
          - "--profile=black"
          - "--line-length=100"
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        args:
          - "--max-line-length=100"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          - "--rcfile=pylintrc"
          # run pylint across multiple cpu cores to speed it up-
          # https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
          - "--jobs=0"
          - "--fail-under=9.0" # minimum score to pass pylint
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
