# coding: utf-8

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from src.api.schemas.pagination_links_first import PaginationLinksFirst
from src.api.schemas.pagination_links_last import PaginationLinksLast
from src.api.schemas.pagination_links_next import PaginationLinksNext
from src.api.schemas.pagination_links_prev import PaginationLinksPrev


class PaginationLinks(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PaginationLinks - a model defined in OpenAPI

        first: The first of this PaginationLinks [Optional].
        _self: The _self of this PaginationLinks.
        prev: The prev of this PaginationLinks [Optional].
        next: The next of this PaginationLinks [Optional].
        last: The last of this PaginationLinks [Optional].
    """

    first: Optional[PaginationLinksFirst] = Field(alias="first", default=None)
    self: PaginationLinksFirst = Field(alias="self_")
    prev: Optional[PaginationLinksPrev] = Field(alias="prev", default=None)
    next: Optional[PaginationLinksNext] = Field(alias="next", default=None)
    last: Optional[PaginationLinksLast] = Field(alias="last", default=None)


PaginationLinks.update_forward_refs()
